import ui.rsc_rc
from PySide2 import QtCore, QtGui, QtWidgets


class Ui_checkon(object):
    def setupUi(self, checkon):
        checkon.setObjectName("checkon")
        checkon.resize(960, 700)
        checkon.setStyleSheet("QWidget#centralwidget\n"
                              "{\n"
                              "background-color: rgb(255, 255, 255);\n"
                              "}")
        self.centralwidget = QtWidgets.QWidget(checkon)
        self.centralwidget.setObjectName("centralwidget")
        self.photograph = QtWidgets.QToolButton(self.centralwidget)
        self.photograph.setGeometry(QtCore.QRect(730, 210, 200, 180))
        self.photograph.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/img/photograph.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.photograph.setIcon(icon)
        self.photograph.setIconSize(QtCore.QSize(240, 180))
        self.photograph.setAutoRaise(True)
        self.photograph.setObjectName("photograph")
        self.out = QtWidgets.QToolButton(self.centralwidget)
        self.out.setGeometry(QtCore.QRect(750, 579, 161, 81))
        self.out.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/img/out.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.out.setIcon(icon1)
        self.out.setIconSize(QtCore.QSize(147, 70))
        self.out.setAutoRaise(True)
        self.out.setObjectName("out")
        self.on_duty = QtWidgets.QToolButton(self.centralwidget)
        self.on_duty.setGeometry(QtCore.QRect(20, 550, 200, 54))
        self.on_duty.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/img/on_duty.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_duty.setIcon(icon2)
        self.on_duty.setIconSize(QtCore.QSize(200, 54))
        self.on_duty.setAutoRaise(True)
        self.on_duty.setObjectName("on_duty")
        self.ring_out = QtWidgets.QToolButton(self.centralwidget)
        self.ring_out.setGeometry(QtCore.QRect(475, 550, 200, 54))
        self.ring_out.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/img/ring_out.png"),
                        QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.ring_out.setIcon(icon3)
        self.ring_out.setIconSize(QtCore.QSize(200, 54))
        self.ring_out.setAutoRaise(True)
        self.ring_out.setObjectName("ring_out")
        self.t11 = QtWidgets.QLabel(self.centralwidget)
        self.t11.setGeometry(QtCore.QRect(31, 601, 75, 33))
        self.t11.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t11.setObjectName("t11")
        self.t21 = QtWidgets.QLabel(self.centralwidget)
        self.t21.setGeometry(QtCore.QRect(31, 646, 75, 33))
        self.t21.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t21.setObjectName("t21")
        self.t12 = QtWidgets.QLabel(self.centralwidget)
        self.t12.setGeometry(QtCore.QRect(106, 600, 214, 35))
        self.t12.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t12.setObjectName("t12")
        self.t22 = QtWidgets.QLabel(self.centralwidget)
        self.t22.setGeometry(QtCore.QRect(106, 645, 214, 35))
        self.t22.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t22.setText("")
        self.t22.setObjectName("t22")
        self.t14 = QtWidgets.QLabel(self.centralwidget)
        self.t14.setGeometry(QtCore.QRect(550, 599, 214, 35))
        self.t14.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t14.setObjectName("t14")
        self.t13 = QtWidgets.QLabel(self.centralwidget)
        self.t13.setGeometry(QtCore.QRect(475, 600, 75, 33))
        self.t13.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t13.setObjectName("t13")
        self.t24 = QtWidgets.QLabel(self.centralwidget)
        self.t24.setGeometry(QtCore.QRect(550, 644, 214, 35))
        self.t24.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t24.setText("")
        self.t24.setObjectName("t24")
        self.t23 = QtWidgets.QLabel(self.centralwidget)
        self.t23.setGeometry(QtCore.QRect(475, 645, 75, 33))
        self.t23.setStyleSheet("font: 25px \"微软雅黑\";\n"
                               "color: rgb(112, 112, 112);")
        self.t23.setObjectName("t23")
        self.camera = QtWidgets.QLabel(self.centralwidget)
        self.camera.setGeometry(QtCore.QRect(30, 10, 641, 481))
        self.camera.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.camera.setText("")
        self.camera.setObjectName("camera")
        self.nameinfo = QtWidgets.QLabel(self.centralwidget)
        self.nameinfo.setGeometry(QtCore.QRect(120, 510, 65, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameinfo.setFont(font)
        self.nameinfo.setStyleSheet("font: 25px \"微软雅黑\";\n"
                                    "color: rgb(112, 112, 112);")
        self.nameinfo.setObjectName("nameinfo")
        self.numinfo = QtWidgets.QLabel(self.centralwidget)
        self.numinfo.setGeometry(QtCore.QRect(370, 510, 65, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.numinfo.setFont(font)
        self.numinfo.setStyleSheet("font: 25px \"微软雅黑\";\n"
                                   "color: rgb(112, 112, 112);")
        self.numinfo.setObjectName("numinfo")
        self.nameinfo_2 = QtWidgets.QLabel(self.centralwidget)
        self.nameinfo_2.setGeometry(QtCore.QRect(190, 510, 171, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameinfo_2.setFont(font)
        self.nameinfo_2.setStyleSheet("font: 25px \"微软雅黑\";\n"
                                      "color: rgb(112, 112, 112);")
        self.nameinfo_2.setText("")
        self.nameinfo_2.setObjectName("nameinfo_2")
        self.nameinfo_3 = QtWidgets.QLabel(self.centralwidget)
        self.nameinfo_3.setGeometry(QtCore.QRect(440, 510, 211, 35))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.nameinfo_3.setFont(font)
        self.nameinfo_3.setStyleSheet("font: 25px \"微软雅黑\";\n"
                                      "color: rgb(112, 112, 112);")
        self.nameinfo_3.setText("")
        self.nameinfo_3.setObjectName("nameinfo_3")
        checkon.setCentralWidget(self.centralwidget)

        self.retranslateUi(checkon)
        QtCore.QMetaObject.connectSlotsByName(checkon)

    def retranslateUi(self, checkon):
        _translate = QtCore.QCoreApplication.translate
        checkon.setWindowTitle(_translate("checkon", "MainWindow"))
        self.t11.setText(_translate("checkon", "应到："))
        self.t21.setText(_translate("checkon", "实到："))
        self.t12.setText(_translate("checkon", "8：00"))
        self.t14.setText(_translate("checkon", "5：00"))
        self.t13.setText(_translate("checkon", "应退："))
        self.t23.setText(_translate("checkon", "实退："))
        self.nameinfo.setText(_translate("checkon", "姓名："))
        self.numinfo.setText(_translate("checkon", "学号："))
